# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Land Development Toolbox
                                 A QGIS plugin
 Implementation of Epanet within QGIS3.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-06-28
        copyright            : (C) 2018 by Greg Leonard
        email                : greg.leonard@otago.ac.nz
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Greg Leonard'
__date__ = '2018-06-28'
__copyright__ = '(C) 2018 by Greg Leonard'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Qgs3Epanet class from file Qgs3Epanet.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .LdtoolboxPlugin import LdtoolboxPlugin
    return LdtoolboxPlugin(iface)
