# -*- coding: utf-8 -*-

"""
/***************************************************************************
 Ldtoolbox
                                 A QGIS plugin
 Implementation of Epanet and SWMM within QGIS3.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-06-28
        copyright            : (C) 2018 by Greg Leonard
        email                : greg.h.leonard@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Greg Leonard'
__date__ = '2018-06-28'
__copyright__ = '(C) 2018 by Greg Leonard'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import sys
import inspect
from PyQt5.QtGui import QIcon
from qgis.core import QgsProcessingAlgorithm, QgsApplication
from .LdtoolboxProvider import LdtoolboxProvider

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class LdtoolboxPlugin(object):

    def __init__(self,iface):
        self.provider = LdtoolboxProvider()

    def initGui(self):
        QgsApplication.processingRegistry().addProvider(self.provider)
    def icon(self):
        return QIcon(":/plugins/ldtoolbox/engineer.png")

    def unload(self):
        QgsApplication.processingRegistry().removeProvider(self.provider)
