# -*- coding: utf-8 -*-

"""
/***************************************************************************
 Qgs3Epanet Post Processing
                                 A QGIS plugin
 Implementation of Epanet within QGIS3.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        Date                 : July 2018
        Copyright            : (C) 2018 by Greg Leonard
        Email                : greg.h.leonard@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Greg Leonard'
__date__ = 'July 2018'
__copyright__ = '(C) 2018 by Greg Leonard'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import getpass
import io
import datetime
import re
import subprocess
from operator import itemgetter
from numpy import mean
#from processing.core.ProcessingLog import ProcessingLog
from processing.core.ProcessingConfig import ProcessingConfig, Setting
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import QCoreApplication,QVariant
from qgis.core import (QgsProcessing,
                       QgsMessageLog,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingUtils,
                       QgsProcessingParameterString,
                       QgsProcessingParameterDefinition,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterVectorLayer,
                       QgsDefaultValue,
                       QgsVectorLayer,
                       QgsProject,
                       QgsField,
                       QgsFields,
                       QgsWkbTypes,
                       QgsFeature,
                       QgsVectorLayerJoinInfo,
                       QgsProcessingParameterFeatureSink)

class Qgs3PostProcessEpanet(QgsProcessingAlgorithm):
    JUNCTIONS  = 'Junctions'
    PIPES = 'Pipes'
    def initAlgorithm(self, config):
        """
        """

    def processAlgorithm(self, parameters, context, feedback):

        layers = [layer for layer in QgsProject.instance().mapLayers().values()]
        for layer in layers:
            if layer.name()=='NodeTimeAgg':
                lyr1=layer
                break
        lyr2 = QgsProject.instance().mapLayersByName(self.JUNCTIONS)[0]

        joinObject = QgsVectorLayerJoinInfo()
        joinObject.setJoinFieldName('Node')
        joinObject.setTargetFieldName('dc_id')
        joinObject.setUsingMemoryCache(True)
        joinObject.setJoinLayer(lyr1)
        joinObject.setJoinFieldNamesSubset(['MaxPressure','MinPressure','MaxHead','MinHead'])
        lyr2.addJoin(joinObject)


        for layer in layers:
            if layer.name()=='LinkTimeAgg':
                lyr1=layer
                break
        lyr2 = QgsProject.instance().mapLayersByName(self.PIPES)[0]

        joinObject = QgsVectorLayerJoinInfo()
        joinObject.setJoinFieldName('Link')
        joinObject.setTargetFieldName('dc_id')
        joinObject.setUsingMemoryCache(True)
        joinObject.setJoinLayer(lyr1)
        joinObject.setJoinFieldNamesSubset(['AvgFlow','AvgVelocity','AvgHeadloss'])
        lyr2.addJoin(joinObject)
        return{}

    def name(self):
        return 'epanetpostprocess'
    def tr(self, string):
        return QCoreApplication.translate('epanetpostprocess', string)

    def icon(self):
        return QIcon(":/plugins/ldtoolbox/epanet.png")

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr('Postprocess EPANET simulation')

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'EPANET'

    def createInstance(self):
        return Qgs3PostProcessEpanet()
